### ISSUE TITLE
Web service: Prototype

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-proc#13]
Full web service should meet the requirements specified in Issue #8.  This issue describes what we would need from a prototype of the service:

Should ask for user input and generate a valid drone.yml file with the following information:
- [x] Input files: A list of files to `git annex get ...` after `git clone` is complete.  Empty value should imply all files.
- [x] Processing step: A single script line would be enough for a prototype.
- [x] Output files: A list of files to `git add ...` (annex filtering could be done using a default config) followed by `git push`.

**Comment by mrinalwahal** [comment]
All the above requirements are fulfilled. Except processing step. Wouldn't take long for me to add it. Let's discuss this in our next call.

**Comment by mrinalwahal** [comment]
Allow specifying `git-annex` files for the user to avoid annexing all the .nix files. (Same way for current file inputs -- make 'em multiple files)

**Comment by achilleas-k** [comment]
Closed by #14
