### ISSUE TITLE
Enable Docker Secrets to store user's Private Keys

### ISSUE THREAD

**Issue by mrinalwahal** [G-Node/gin-proc#15]
As of now the micro-service works on my host machine, therefore, access to ssh keys isn't an issue, however, turning the service into a docker image, would require us to mount external volumes to access user's ssh keys or enable something like docker secrets for the same.

**Comment by mrinalwahal** [comment]
Can we close this issue? Since we are installing Drone secrets through its API in #25.

**Comment by achilleas-k** [comment]
Closing as outdated.
