### ISSUE TITLE
Authenticate user from GIN web app

### ISSUE THREAD

**Issue by mrinalwahal** [G-Node/gin-proc#16]
As for the testing environment, I'm authenticating the dev user using a `personal access token` designed manually. Eventually, we'll have to authenticate the user using their GIN username and password, just the way Drone does it.

**Comment by mrinalwahal** [comment]
This is done. `gin-proc` micro-service now authenticates the user with GIN credentials and automatically installs a personal access token for future use. We can close this issue in the end.

**Comment by achilleas-k** [comment]
Done in #14
