### ISSUE TITLE
Code quality and style

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-proc#18]
I intend to add automatic checks on pull requests for these, but for now, here's a list of some of the code style issues that need to be addressed:
- `os.system()` should never be used.  All instances should be replaced by `subprocess.call()` or `check_output()`.
- Indent Python code with 4 spaces (no tabs).
- Adhere to PEP8 strictly.
- Concatenate strings that represent filesystem paths using `os.path.join()`.
- Commented out code should be removed, or if there's a good reason for it to remain, it shouldn't be a `"""string"""` but a `# comment`.

**Comment by mrinalwahal** [comment]
Roger. I've set up pylint and pep8. Will follow this from now on. All instances of `os.system()` have been removed. You can test it now.

**Comment by achilleas-k** [comment]
Done.
