### ISSUE TITLE
Write CI config in yaml format from python

### ISSUE THREAD

**Issue by mrinalwahal** [G-Node/gin-proc#19]
Currently I'm using a workaround to read the default saved template files of CI configurations and adding required lines after detecting hash break-points. Ex. `#add-annex-files`

I feel this is an unprofessional way of doing it. Though, it does the job for now, it would be more professional to do this in a more hackable and clean manner using something like [pyYAML](https://pyyaml.org/wiki/PyYAMLDocumentation#FrequentlyAskedQuestions).

This will also allow us to read the yaml configs at a later stage and only replace the values that we want to, instead of writing and replacing the entire config - as we are doing currently.

**Comment by achilleas-k** [comment]
I agree.  Read in the entire yaml file.  Since it's our own template, the service should know which keys need which user-defined values.  Then you just write it back with the replaced information.

**Comment by achilleas-k** [comment]
Closed in #26
