### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by mrinalwahal** [G-Node/gin-proc#27]
We can design a `debug` more for the flask server and enable it with an env variable, something like `DEBUG=TRUE` during launching of `gin-proc` container by the user.

Or we could:

- [x] Enable logging 
- [ ] And rotate those logs periodically in user's mounted volumes.

May not be a priority right now, but I think its a professional principle to go by. It should make it easier for the user's to debug their server's problem's later.

**Comment by achilleas-k** [comment]
Print logging is ok for now since when running in Docker, we can access the output using `docker log...`.  We could have the backend check for an env var (e.g., `LOG_DIR`) and write files to that location if it's specified, otherwise print log by default.

**Comment by mrinalwahal** [comment]
Finished in #41

**Comment by achilleas-k** [comment]
Looks good.  I'll test it locally and close.
