### ISSUE TITLE
Enable Volume caching for faster CI jobs

### ISSUE THREAD

**Issue by mrinalwahal** [G-Node/gin-proc#4]
As of now, all pipelines run from scratch in a separate container, which can be avoided by storing intermediate temporary build files created by being cached, and eventually speed up the build job completion.

**Comment by mrinalwahal** [comment]
Git-annex-add is enabled. Build jobs are failing due to another reason. I'll close the issue once I have at least one successful build job.

**Comment by mrinalwahal** [comment]
This caching needs to be discussed in one of our following calls.

**Comment by achilleas-k** [comment]
In #45, the cloned repositories are cached and reused when available.
