### ISSUE TITLE
Key description should mention gin-proc

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-proc#51]
The name/description of the key that the gin-proc service installs for the user should be called `gin-proc` or something similar to make its purpose clear to the user.

https://github.com/G-Node/gin-proc/blob/9690416f2b29c3573fe3a062d1ee85c9be418468/back-end/service.py#L32

**Comment by mrinalwahal** [comment]
This issue is already resolved. The original file has the variable value as `gin-proc`.
