### ISSUE TITLE
User defined output files push

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/gin-proc#7]
Use `drone.yml` to define which files from the CI build output should be pushed after a build is done.

**Comment by mrinalwahal** [comment]
Added this functionality. I'm just getting merge conflicts while pushing to `gin-proc` branch due to .snakemake log files. Trying to ignore those from being committed.

**Comment by mrinalwahal** [comment]
Allow multiple files from the front-end, no matter how horrible it feels to do so.

**Comment by achilleas-k** [comment]
Basic functionality is there (in #14) but could use some improvements (multiple files, etc)

**Comment by mrinalwahal** [comment]
Done and pushed.

**Comment by achilleas-k** [comment]
Closed by #14
